# Generated by Django 5.2.4 on 2025-07-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipe_name', models.CharField(max_length=100)),
                ('receipe_dis', models.TextField()),
                ('receipe_img', models.ImageField(upload_to='recipename')),
            ],
        ),
    ]
