# Generated by Django 5.2.4 on 2025-07-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='receipe_img',
            field=models.ImageField(upload_to='recipe/recipename'),
        ),
    ]
