# Generated by Django 5.2.4 on 2025-07-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0003_alter_recipe_receipe_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='receipe_img',
            field=models.ImageField(upload_to='recipe'),
        ),
    ]
