# Generated by Django 5.1.3 on 2025-07-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0007_alter_recipe_receipe_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='receipe_img',
            field=models.ImageField(blank=True, upload_to='receipe'),
        ),
    ]
